import { Project, ProjectStatus, ProjectType } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'ff_master',
    title: '이차함수 표준형 변환',
    description: 'Gemini를 활용하여 이차함수 표준형 변환 문제를 무제한으로 생성하고, 단계별 풀이를 제공합니다.',
    status: ProjectStatus.Success,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/ff_master/',
    goal: 'Gemini로 문제 무제한 제공, 정수 계수, 단계별 풀이 제공, 패들렛 링크 연동.',
  },
  {
    id: 'f_yeoju3',
    title: '이차함수 계수 탐구',
    description: 'GeoGebra와 연동하여 이차함수의 각 계수(a, b, c)가 그래프에 미치는 영향을 직관적으로 탐구합니다.',
    status: ProjectStatus.Success,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/f_yeoju3/',
    goal: 'a,b,c 계수별 탭 분리, GeoGebra 앱 연동 및 전체 화면 지원, 최종 정리본 제공, 팅커벨 보드 연동.',
  },
  {
    id: 'yjfc',
    title: '삼각비와 축구 시야각',
    description: '축구 경기장 시야각 문제를 통해 삼각비의 실용적 활용을 단계별로 탐구하는 학습 자료입니다.',
    status: ProjectStatus.Success,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/yjfc/',
    goal: '단계별 탐구 과정, 현재 단계의 삼각형 하이라이트, 각도 변경 시 시야각 자동 계산.',
  },
  {
    id: '2025history',
    title: '3학년 수업 활동 공개',
    description: '앨범 형식으로 3학년 학생들의 다양한 수업 활동 모습을 영상과 사진으로 생생하게 전달합니다.',
    status: ProjectStatus.Success,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/2025history/',
    goal: '메인 앨범 클릭 시 활동 확인, 영상과 사진첩 구성, 소개 글 수정 기능.',
  },
  {
    id: 'easymath_function',
    title: '이차함수 수업 안내',
    description: 'GitHub에서 코드 수정 없이 AI Studio를 통해 생성된 코드로 바로 웹페이지를 만드는 과정을 보여줍니다.',
    status: ProjectStatus.Success,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/easymath_function/',
    goal: 'Google AI Studio에서 생성된 코드를 GitHub Pages로 바로 배포하는 과정 시연.',
  },
  {
    id: 'praise',
    title: '칭찬 스티커판',
    description: '반별, 학생별 칭찬 스티커판을 관리하고 순위를 매기는 어플리케ATION입니다.',
    status: ProjectStatus.Failure,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/praise/',
    goal: '반별 칭찬스티커판, 1등 반/학생 선정, 메모 기능과 함께 점수 부여, 누가 기록 관리.',
    failurePoint: '데이터베이스 없이 `localStorage`를 사용해 구현하여, 다른 기기나 브라우저에서는 데이터가 연동되지 않고, 캐시 삭제 시 데이터가 유실되는 문제가 발생했습니다.',
  },
  {
    id: 'manners_quiz',
    title: '예의 범절 문항지',
    description: '학생들이 예의 범절에 대한 설문에 참여하고, 선생님은 결과를 확인할 수 있는 시스템입니다.',
    status: ProjectStatus.Failure,
    type: ProjectType.Link,
    link: 'https://easypie65.github.io/school_attitude/',
    goal: '학생 로그인/로그아웃, 설문 제출, 교사용 비밀번호를 통한 결과 확인 기능.',
    failurePoint: '칭찬 스티커판과 마찬가지로 `localStorage` 기반으로 제작되어, 같은 기기(브라우저)에서만 학생들의 제출 결과를 확인할 수 있는 한계가 있었습니다.',
  },
];